security:
    erase_credentials: false
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
  
    role_hierarchy:
        ROLE_ADMIN:         ROLE_USER
        ROLE_SUPER_ADMIN:   ROLE_ADMIN
        
    access_control:
        - { path: ^/$, role: ROLE_USER } 
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }

    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle, fr3d_ldapbundle]
        fr3d_ldapbundle:
            id: fr3d_ldap.security.user.provider
        fos_userbundle:
            id: fos_user.user_provider.username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            fr3d_ldap:  ~
            security: false
            form_login:
                always_use_default_target_path: true
                default_target_path: /
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true

        main:
            pattern: ^/
            fr3d_ldap:  ~
            form_login:
                always_use_default_target_path: true
                default_target_path: /
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true
  
  